fixtures:
  forge_modules:
    yumrepo_core:
      repo: puppetlabs/yumrepo_core
    stdlib:
      repo: puppetlabs/stdlib
    augeasproviders_core:
      repo: puppet/augeasproviders_core
    augeasproviders_shellvar:
      repo: puppet/augeasproviders_shellvar
    systemd:
      repo: puppet/systemd
    rsyslog:
      repo: saz/rsyslog
    network:
      repo: puppet/network
    filemapper:
      repo: puppet/filemapper
  symlinks:
    mofed: "#{source_dir}"
