fixtures:
  repositories:
    yumrepo_core:
      repo: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
    stdlib:
      repo: https://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: v8.6.0
    augeasproviders_core:
      repo: https://github.com/voxpupuli/puppet-augeasproviders_core.git
    augeasproviders_shellvar:
      repo: https://github.com/voxpupuli/puppet-augeasproviders_shellvar.git
    systemd:
      repo: https://github.com/voxpupuli/puppet-systemd.git
    rsyslog:
      repo: https://github.com/saz/puppet-rsyslog.git
    network:
      repo: https://github.com/example42/puppet-network.git
      ref: v3.6.1
  symlinks:
    mofed: "#{source_dir}"
