---
.github/workflows/ci.yaml:
  acceptance_matrix: false
.gitlab-ci.yml:
  delete: true
appveyor.yml:
  delete: true
spec/acceptance/nodesets/debian-11.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-2004.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-2204.yml:
  delete: true
